### ISSUE TITLE
Switches don't work in "Invite a team to organization"

### ISSUE THREAD

**Issue by SofiaSazonova** [data-dot-all/dataall#1015] opened 2024-01-26 15:26 UTC
### Describe the bug

When I invite a team to join the organization, there are two switched: 
"Link environments to this organization" and 'Invite teams to this organization". They are always 'off' and non responsive.

### How to Reproduce

Prereq: 
1. You have an Organization
2. You are in the cognito group different from already included into this Org

Open Organization page, "Teams" tab. Click "Invite team".
Chose the team you want to invite.
Try to click on switches.

### Expected behavior

Switches should work) 

OR 

If the switches are off by design, the tooltip or other info message should be displayed.

### Screenshots

![image](https://github.com/data-dot-all/dataall/assets/1146495/0aa5d2de-6d2a-44e7-8a23-80d1dfa7bf13)

### OS

macOs Sonoma 14.2

### Python version

3.11

### AWS data.all version

2.2.0

**Comment by noah-paige** [comment] 2024-01-26 15:30
Believe duplicate of https://github.com/data-dot-all/dataall/issues/373 - tracked for 2.3.1

**Closed** 2024-01-26 15:45 UTC
