### ISSUE TITLE
Shares created on same account as the IAM role grant too much access

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1206] opened 2024-04-22 09:57 UTC
### Describe the bug

If a consumer role is registered on an environment and then a share is created on same environment using this role for an S3 bucket then the IAM role is granted S3:* permissions allowing it all permissions to the S3 bucket.

### How to Reproduce

1. register consumer role on an environment
2. create an S3 bucket share with this role on the same environment
3. test if you can use the role to write to the bucket

### Expected behavior

Writing to the bucket should fail

### OS

N/A

### Python version

3.11

### AWS data.all version

2.3

**Comment by dlpzx** [comment] 2024-04-24 07:09
Hi @zsaltys I think this issue is a duplicate of https://github.com/data-dot-all/dataall/issues/1172. We'll close this issue in favor of the initial one. We tagged it as high priority and will pick it up as soon as possible

**Closed** 2024-04-24 07:09 UTC
Labels: status: duplicate
