### ISSUE TITLE
No effect on session after setting cognito_user_session_timeout_inmins

### ISSUE THREAD

**Issue by shivalkarrahul** [data-dot-all/dataall#1296] opened 2024-05-22 12:22 UTC
### Describe the bug

Hello Team,

We are using v2.2.0 and have set cognito_user_session_timeout_inmins to 60. As per the doc - 
cognito_user_session_timeout_inmins -> The number of minutes to set the refresh token validity time for user session’s in Cognito before a user must re-login to the data.all UI (default: 43200 - i.e. 30 days)
Doc Link: https://data-dot-all.github.io/dataall/deploy-aws/

However, we still see that the session still remains active and the user is not asked to re-login.

### How to Reproduce

```
edit cdk.json
set "cognito_user_session_timeout_inmins": 60 in DeploymentEnvironments section
```

### Expected behavior

The user must be asked to re-login after 60 minutes.

### OS

NA

### Python version

NA

### AWS data.all version

2.2.0

**Comment by SofiaSazonova** [comment] 2024-05-23 13:28
Hi @shivalkarrahul !
Thanks for opening issue! Can you confirm, that both `Access token expiration` and `ID token expiration` values in AWS Cognito are set less than 60 mins? We will test this behaviour and will be back with more detailed answer.

**Comment by SofiaSazonova** [comment] 2024-05-23 14:45
I couldn't reproduce the bug, so please, provide more details about your deployment.

**Comment by shivalkarrahul** [comment] 2024-05-24 05:12
Hello @SofiaSazonova ,

Thanx for your reply.
Here is what we have in Incognito. Refresh token expiration is still 30 days.

<img width="331" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/1a32d2bb-bdad-4f96-8b5c-0bfb0a2a9057">

![image](https://github.com/data-dot-all/dataall/assets/19208841/2df61a3a-a9cf-4cc8-8141-edfe9fae250d)

**Comment by SofiaSazonova** [comment] 2024-05-24 13:13
Oh, I see. The problem is not, that timeout doesn't work, but it's not set right!

**Comment by SofiaSazonova** [comment] 2024-05-24 14:23
@shivalkarrahul Could you please confirm, that after you commit and push this changes of `cdk.json` into CodePipelines, the pipeline was build without any errors?

**Comment by shivalkarrahul** [comment] 2024-05-28 09:28
Hello @SofiaSazonova ,
Yes, I confirm that the pipeline completed successfully.

**Comment by anmolsgandhi** [comment] 2024-06-11 02:48
Hi @shivalkarrahul , is this issue resolved ? if so can we close this issue?

**Comment by anmolsgandhi** [comment] 2024-06-14 16:56
Closing this issue as it seems to be resolved now, feel free to reopen if you have questions or still need any help on this issue.

**Closed by anmolsgandhi** 2024-06-14 16:56 UTC
Labels: type: bug, status: can't reproduce, type: question, status: closing-soon, status: not-picked-yet, status: needs more info
