### ISSUE TITLE
Missing permissions when first enabling Worksheets module

### ISSUE THREAD

**Issue by rbernotas** [data-dot-all/dataall#944] opened 2024-01-05 02:25 UTC
### Describe the bug

With a deployed instance of data.all that never had Worksheets enabled, if you then enable Worksheets in the config.json, the following permissions do not exist, and are not applied to tenants and resources that already exist:

- GET_WORKSHEET
- DELETE_WORKSHEET
- UPDATE_WORKSHEET
- RUN_WORKSHEET_QUERY
- RUN_ATHENA_QUERY
- MANAGE_WORKSHEETS

This causes the following issues:

- Worksheets can be created, but not used, due to the lack of the GET_WORKSHEET permission being applied to the resource.
- In the admin view, if you try to view the permissions for any given tenant team, it leads to a blank screen and you can no longer set permissions for the teams (this is due to the lack of the MANAGE_WORKSHEETS tenant permission).
- In the environment team invite popup, the permission for running athena queries is not available or set.  Even if you had GET_WORKSHEET available, you would not be able to run the query in the sheet.
- Worksheets can be created, but not deleted or updated.
- There may be other issues, but these are the most apparent.

The following manual remediations need to take place:

1.  Add the permissions to the RDS db like (your permissionUris and created timestamps may need to differ, and where "dataalldb" is replaced with the name of your db):

--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('mv46k9bt', 'GET_WORKSHEET', 'RESOURCE', 'GET_WORKSHEET', '2024-01-04 02:42:05.916708');                                       
--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('mpqkwrq4', 'DELETE_WORKSHEET', 'RESOURCE', 'DELETE_WORKSHEET', '2024-01-04 02:42:05.916708');
--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('eiw8iujo', 'UPDATE_WORKSHEET', 'RESOURCE', 'UPDATE_WORKSHEET', '2024-01-04 02:42:05.916708');
--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('f0ngt5mi', 'RUN_WORKSHEET_QUERY', 'RESOURCE', 'RUN_WORKSHEET_QUERY', '2024-01-04 02:42:05.916708');
--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('d0cgt7ab', 'RUN_ATHENA_QUERY', 'RESOURCE', 'Run Worksheet Athena queries on this environment', '2024-01-04 02:42:05.916708');
--INSERT INTO dataalldb.permission ("permissionUri", "name", "type", "description", "created") VALUES ('68r738xw', 'MANAGE_WORKSHEETS', 'TENANT', 'Manage worksheets', '2024-01-04 02:42:05.916708');

2.  For each team sid, add the MANAGE_WORKSHEETS permission (where you need to adjust the permissionUri to match your MANAGE_WORKSHEETS permissionUri, and the sid's to match your sid's, and update the created date):

-- Use the following to get all sids.
--select * from dataalldb.tenant_policy;                                                                                                           
-- Then for each sid:
--INSERT INTO dataalldb.tenant_policy_permission ("sid", "permissionUri", "created") VALUES ('coly7hc8', '68r738xw', '2024-01-04 02:42:05.916708');

3.  For each environment sid in resource policy permissions, add the RUN_ATHENA_QUERY permission (where you need to adjust the permissionUri to match your RUN_ATHENA_QUERY permissionUri, and the sid's to match your sid's, and update the created date):

-- Use the following to get all sids.
--select * from dataalldb.resource_policy where "resourceType"='Environment';                                                                        
-- Then for each sid:
--INSERT INTO dataalldb.resource_policy_permission ("sid", "permissionUri", "created") VALUES ('kr5xbit4', 'd0cgt7ab', '2024-01-04 02:42:05.916708');

After these manual steps, you should be able to properly use Worksheets and have no issues working with team permissions in the Admin or Env views.

This might also occur with a similar scenario turning on other modules which require permissions, like Dashboards, or others where you have never enabled the modules, but we have not yet tested that.

### How to Reproduce

Reproduced with v2.2, although this was also seen in earlier 2.x versions.

Create a data.all instance where you have the Worksheets module turned off from the initial deploy in config.json, like:

        },
        "worksheets": {
            "active": false
        },

After successfully deploying this, create some teams/envs, verify you can administer permissions for tenant teams from the UI, verify that you can administer permissions for env teams from the UI, etc.

Then set Worksheets module on from config.json like:

        "worksheets": {
            "active": true
        },

...and redeploy.

Try to use Worksheets and administer permissions as described in the issue description, and encounter the issues.

### Expected behavior

Ideally when toggling the module, one wouldn't need to manually apply these permissions to tenant teams and envs, or have to create the permissions.

Perhaps always create the permissions even if a module isn't turned on... then at least the permissions are always there.

For permissions missing from tenant teams and envs sids, if you turn a module like Worksheets on, I think at a minimum the UI shouldn't fail to load permissions...at a minimum they should be default off but the UI should allow them to be turned on without error.  Ideally for a module like Worksheets, it feels like the permissions should be applied to all teams and envs to be on/available by default, but I'm sure there are some users/use cases where this wouldn't be desirable, so perhaps some discussion is necessary.  The minimum case however should be that the UI should function as normal without errors even if the permissions need to be adjusted in the UI after the fact.  It should also not be necessary to make manual database updates to apply the permissions to teams and envs that existed prior to the module being turned on.  It's also important to note that if Worksheets are turned on after many teams and envs are created (perhaps hundreds or thousands), it would be extremely cumbersome to flip on the worksheet permissions in the UIs for all those teams and envs--seems like there needs to be a way through the admin UI to bulk apply a particular permission to all envs or all teams.

### OS

n/a

### Python version

n/a

### AWS data.all version

2.2

**Comment by noah-paige** [comment] 2024-01-05 21:57
After doing some testing to see if I could reproduce the above, I found the following:

When disabling, removing the module-specific permissions, and re-enabling both `worksheets` and `mlstudio` modules I saw the same behavior as above where the permissions were not added but only for Resource Type Permissions (Tenant Type Permission - e.g. `MANAGE_WORKSHEETS`  were added appropriately)

When printing out some debugging statements in the `init_permissions()` method which is where the new permissions should be added (`backend/dataall/core/permissions/db/permission_repositories.py`) I saw the following counts:
- count_resource_permissions: 106 (this is the # of entries in the Permissions Table in RDS Aurora)
- RESOURCES_ALL: 83 (this is the total # of resource type permissions used by data.all)

When looking at the RDS tables I saw a number of duplicates in the `permissions` Aurora RDS Table - this could just be from my sandbox deployment and tinkering with the data.all DB manually but would be curious if you also are seeing duplicate Permissions names in that table

Currently, testing to see if `count_resource_permissions < RESOURCES_ALL` if the permissions will be added appropriately - as it should given logic in the `def init_permissions()` method

**Comment by rbernotas** [comment] 2024-01-08 15:26
I did have to add the tenant permission for MANAGE_WORKSHEETS manually, this was not added automatically for us.

Currently we have 83 records int he permission table for this instance after enabling Worksheets and manually adding the resource and tenant permissions for Worksheets.  Working with the permissions table data, we have no duplicate permissions--they are all unique.

**Comment by Macklon** [comment] 2024-01-29 05:54
We are facing similar issue mentioned above when we enabled Dashboards module.

@noah-paige 
"Currently, testing to see if count_resource_permissions < RESOURCES_ALL if the permissions will be added appropriately - as it should given logic in the def init_permissions() method"
Were you able to fix the issue? or do we have to follow manual remediations steps which are mentioned above by @rbernotas (need to replace permission specific to dashboards)

**Comment by petrkalos** [comment] 2024-03-27 15:49
I've been looking into it and I think I have found the root cause.

`init_permissions` is being called on every request and decides to or not new permissions based on the count of the existings perms (more details on the logic can be found [here](https://github.com/data-dot-all/dataall/blob/a35a4c7c4de78f0b38502882382f07aeac815b3c/backend/dataall/core/permissions/db/permission_repositories.py#L76)).

As @noah-paige noticed this count is not a reliable indicator because there might be duplicates in the db. The reason we see the duplicates is because when we [save permissions](https://github.com/data-dot-all/dataall/blob/a35a4c7c4de78f0b38502882382f07aeac815b3c/backend/dataall/core/permissions/db/permission_repositories.py#L58) we don't do it atomically. To further elaborate we first run a `find_permission_by_name` (a SELECT) and then if not found we INSERT the new permission. If two concurrent request hit the endpoint and pass the `find_permission_by_name` check they will end up INSERTing the same thing.

I think the correct way forward is to introduce a CustomResource in CDK which will be invoking a handler that will take care of data.all initialization step (permission tables etc). Because that will run once on every deployment we don't care about performance and as such we can do a more exhaustive check (instead of just the count) and INSERT what's not missing.
Furthermore we can use this CustomResource to execute other init or maintenance tasks.

Let me know what you think.

**Comment by dlpzx** [comment] 2024-04-02 13:39
I agree that deciding on the permissions_count is not a reliable way of checking the permissions. But I am not sure we should use a custom resource. Cannot we just re-use the `db-migration` CodeBuild stage in a more clever manner? At the end we are performing updates to RDS table information

**Closed** 2024-04-10 13:46 UTC
Labels: type: bug, priority: medium
