### ISSUE TITLE
Existing dataset stacks update failure after 2.0.0 to 2.6.0 upgrade

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#1588] opened 2024-09-27 12:35 UTC
### Describe the bug

After 2.0.0 to 2.6.0 upgrade existing dataset stacks are not updating.
After debugging we see that stack parameter GlueDatabaseProviderServiceTokenParameter has been updated from hardcoded value ‘/dataall/dataset.environmentUri}/cfn/custom-resources/gluehandler/provider/servicetoken' to ‘/{env.resourcePrefix}/{dataset.environmentUri}/cfn/custom-resources/gluehandler/provider/servicetoken'
And as you can see from attached log file the new changeset is not updating the stack parameter with new path so stack fails. FYI we are using default “dcx” resource prefix.

Is this the expected behavior or do we had one step that was missed during upgradation?

### How to Reproduce

Data All 2.0.0 must be up and running
Create an Organization -> Environment (While creating the Environment, use custom "Resource Prefix" say "xyz")
Create Dataset for this environment.

Upgrade Data All to 2.6.0 from 2.0.0
Once the Upgrade is complete, try to update already created dataset
it fails with the above mentioned Error

### Expected behavior

Data sets created previously under 2.0.0 version (with Environment having custom resource prefix) should be able to update the Data set successfully even after 2.6.0 upgrade

### OS

Mac Sonoma 14.3

### Python version

3.9.13

### AWS data.all version

2.6.0

**Comment by dlpzx** [comment] 2024-09-27 14:45
Hi @sandeephs1 we were able to recreate your issue in our internal deployments and we find the root cause of the problem:
1. In 2.0.0 the Environments and Datasets use an SSM parameter prefixed with dataall `dataall/.../servicetoken`
2. When upgrading to >2.1.0 we update the Environment stack, `dataall/.../servicetoken` is deleted and `dcx/.../servicetoken` is created
3. When updating the Dataset the change set cannot be created because it is comparing `dataall/.../servicetoken` and `dcx/.../servicetoken` and it cannot find the old dataall one. 

The way we worked around this manually was to create the SSM parameter `dataall/.../servicetoken` with the same value as the `dcx/.../servicetoken` one and then update the dataset again. The final dataset uses the correct `dcx/.../servicetoken` but it needed the other one to exists to be able to change it. Now you can delete the manually created SSM parameter. 

This is a manual workaround that helped us understand the issue; but next week we will work on alternatives on how this could be fixed in a more robust way

**Comment by dlpzx** [comment] 2024-10-11 11:42
We have confirmed offline that the workaround was sufficient for users to complete the upgrade. Closing this issue, if needed we can reopen it in the future.

**Closed by dlpzx** 2024-10-11 11:42 UTC
Labels: type: bug, priority: high
